module.exports = [
    {
        id: 1,
        type: 'image',
        content: '/assets/q1.webp',
        question: "Real or AI?",
        answer: 'AI',
        explanation: "Look at the fingers merging together."
    },
    {
        id: 2,
        type: 'text',
        content: "The sunset glowed with a neon hue, unlike any star the galaxy knew...",
        question: "Real Poem or AI?",
        answer: 'AI',
        explanation: "Generated by ChatGPT-5."
    }
];